language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew upgrade xctool
  - pod install
before_script:
  - export RMNETWORK_TEST_ENV="travis"
script:
  - xctool -workspace RMNetworkDemo.xcworkspace -scheme RMNetworkDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
