language: objective-c
before_install: true
  #- brew update
  #- brew upgrade xctool
  #- gem install cocoapods
script:
  - xctool -workspace RMNetworkDemo.xcworkspace -scheme RMNetworkDemo -sdk iphonesimulator7.0 -freshInstall -freshSimulator  ONLY_ACTIVE_ARCH=NO
